# Generated by Django 5.0.6 on 2024-06-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=32)),
                ('definition', models.TextField()),
                ('example', models.TextField()),
                ('alternative_forms', models.CharField(max_length=300)),
                ('copyright', models.CharField(max_length=64)),
                ('origin', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField()),
                ('date_edited', models.DateTimeField()),
                ('key', models.IntegerField()),
            ],
        ),
    ]
