# Generated by Django 5.0.6 on 2024-06-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermModel',
            new_name='Term',
        ),
    ]
