# Generated by Django 5.0.6 on 2024-06-01 09:42

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_rename_termmodel_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='alternative_forms',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='copyright',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='date_added',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='term',
            name='date_edited',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='term',
            name='example',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='origin',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
