# Generated by Django 5.0.6 on 2024-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0003_alter_term_alternative_forms_alter_term_copyright_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='alternative_forms',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='copyright',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='origin',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
