# Generated by Django 5.0.3 on 2024-06-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0004_alter_term_alternative_forms_alter_term_copyright_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
