# Generated by Django 5.0.3 on 2024-06-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0005_term_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='url',
            field=models.CharField(default='undefined', max_length=64, unique=True),
        ),
    ]
